name: noor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  provider: ^6.0.1
  dio: ^4.0.4
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.16
  shared_preferences: ^2.0.9
  location: ^4.2.0
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  map_launcher: ^2.2.0
  just_audio: ^0.9.19


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


